"use strict";
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrderStatus = exports.ReservationStatus = exports.TableStatus = exports.Role = void 0;
exports.Role = {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    WAITER: 'WAITER',
    RECEPTIONIST: 'RECEPTIONIST'
};
exports.TableStatus = {
    AVAILABLE: 'AVAILABLE',
    OCCUPIED: 'OCCUPIED',
    RESERVED: 'RESERVED'
};
exports.ReservationStatus = {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    CANCELLED: 'CANCELLED'
};
exports.OrderStatus = {
    OPEN: 'OPEN',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED'
};
